version: "3.5"
services:
    
  pgdb:
    image: postgres:16
    container_name: db-node-express-template
    hostname: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=node-express-template
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - 5435:5432/tcp
    volumes:
      - "./pg_db:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: production
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
    depends_on:
      pgdb:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app


  