version: "3.5"
services:
    
  pgdb:
    image: postgres:16
    container_name: db-senwata
    hostname: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=senwata
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - 5435:5432/tcp
    volumes:
      - "./pg_db:/var/lib/postgresql/data"


  