import { BOT_MAIL_ADDRESS, BOT_MAIL_PASSWORD } from "../utils/constants";

const nodemailer = require("nodemailer");

export class EmailService {
  constructor() {}

  sendEmail(email: string, subject: string, message: string): boolean {
    //send email here
    //handle emails
    const emailsHandling = {
      botMail: BOT_MAIL_ADDRESS,
      destinator: email,
    };

    let transporter = nodemailer.createTransport({
      // gmail is used here
      host: "smtp.gmail.com",
      port: 587, // 587 -> TLS & 465 -> SSL
      auth: {
        // email adress of your google account
        user: emailsHandling.botMail,
        // password of your google account generated by google
        pass: BOT_MAIL_PASSWORD,
      },
    });

    const mail = {
      from: emailsHandling.botMail,
      to: emailsHandling.destinator,
      subject: subject,
      // we can replace the attribute `text` by `html` if we want that the body of the mail support html syntax
      // html:  '<h1>This email use html</h1>'
      html: message,
    };

    let sendStatus = false;

    transporter.sendMail(mail, (error, info) => {
      if (error) {
        console.log("Error occurred: " + error.message);
        sendStatus = false;
      } else {
        console.log("OTP email sent successfully: " + info.response);
        sendStatus = true;
      }
    });

    return sendStatus;
  }
}
